package day07_test

import (
	day07 "aoc2025/07"
	"testing"
)

var test = `
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
`

func TestPart1(t *testing.T) {
	expect := "21"
	if res := day07.Part1(test); res != expect {
		t.Fatalf("expected %s got %s", expect, res)
	}
}

func TestPart2(t *testing.T) {
	expect := "40"
	if res := day07.Part2(test); res != expect {
		t.Fatalf("expected %s got %s", expect, res)
	}
}
